"use client";

import { useEffect } from "react";
import { toast } from "sonner";

export function WelcomeToast() {
  useEffect(() => {
    if (!document.cookie.includes("welcome-toast=3")) {
      toast("Welcome to Next AI News!", {
        id: "welcome-toast",
        duration: Infinity,
        onDismiss: () => {
          document.cookie += "welcome-toast=3;max-age=31536000";
        },
        description: (
          <>
            All the stories and comments were generated by AI.
            <hr className="my-2" /> This is an example of a full-stack,
            streaming server-rendered Next.js app.{" "}
            <a
              href="https://github.com/rauchg/next-ai-news"
              className="text-[#FF9966]"
              target="_blank"
            >
              Get the Source
            </a>
          </>
        ),
      });
    }
  }, []);

  return null;
}
